/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import clases.ConexionBD;

/**
 *
 * @author MarcosCano
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuEmpleado
     */
    public MenuPrincipal() {
        initComponents();
        
        ConexionBD conexion = ConexionBD.getInstancia();
        conexion.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemCrearVenta = new javax.swing.JMenuItem();
        jMenuItemVisualizarVentas = new javax.swing.JMenuItem();
        jMenuItemEstadoVentas = new javax.swing.JMenuItem();
        jMenuItemContratarServicio = new javax.swing.JMenuItem();
        jMenuItemCancelarServicio = new javax.swing.JMenuItem();
        jMenuItemVisualizarServiciosVigentes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemIniciarLLamada = new javax.swing.JMenuItem();
        jMenuItemHistorialLlamadas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemRegistroCliente = new javax.swing.JMenuItem();
        jMenuItemActualizarCliente = new javax.swing.JMenuItem();
        jMenuItemVisualizarClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRegistroEmpleado = new javax.swing.JMenuItem();
        jMenuItemActualizarEmpleado = new javax.swing.JMenuItem();
        jMenuItemDespidoEmpleado = new javax.swing.JMenuItem();
        jMenuItemVisualizarEmpleados = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAgregarProductoServicio = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemVisualizarProductoServicio = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemCrearReporte = new javax.swing.JMenuItem();
        jMenuItemEstadoReporte = new javax.swing.JMenuItem();
        jMenuItemVisualizarReporte = new javax.swing.JMenuItem();
        jMenuItemAgregarCategoria = new javax.swing.JMenuItem();
        jMenuItemActualizarCategoria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Inicia Sesión");

        jLabel2.setText("Codigo Empleado");

        jLabel3.setText("Contraseña");

        jButton1.setText("Iniciar Sesión");

        jButton2.setText("Olvide mi contraseña");

        jMenu6.setText("Ventas");

        jMenuItemCrearVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemCrearVenta.setText("Crear Venta");
        jMenuItemCrearVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearVentaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemCrearVenta);

        jMenuItemVisualizarVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemVisualizarVentas.setText("Visualizar Ventas");
        jMenuItemVisualizarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarVentasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemVisualizarVentas);

        jMenuItemEstadoVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemEstadoVentas.setText("Estado Ventas");
        jMenuItemEstadoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadoVentasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemEstadoVentas);

        jMenuItemContratarServicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemContratarServicio.setText("Contratar Servicio");
        jMenuItemContratarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContratarServicioActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemContratarServicio);

        jMenuItemCancelarServicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemCancelarServicio.setText("Cancelar Servicio");
        jMenuItemCancelarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCancelarServicioActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemCancelarServicio);

        jMenuItemVisualizarServiciosVigentes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItemVisualizarServiciosVigentes.setText("Visualizar Servicios Vigentes");
        jMenuItemVisualizarServiciosVigentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarServiciosVigentesActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemVisualizarServiciosVigentes);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem2.setText("Reporte de Pagos");
        jMenu6.add(jMenuItem2);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Llamadas");

        jMenuItemIniciarLLamada.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItemIniciarLLamada.setText("Iniciar Llamada");
        jMenuItemIniciarLLamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIniciarLLamadaActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemIniciarLLamada);

        jMenuItemHistorialLlamadas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItemHistorialLlamadas.setText("Historial Llamadas");
        jMenuItemHistorialLlamadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistorialLlamadasActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemHistorialLlamadas);

        jMenuBar1.add(jMenu7);

        jMenu1.setText("Clientes");

        jMenuItemRegistroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItemRegistroCliente.setText("Registrar Nuevo Cliente");
        jMenuItemRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRegistroCliente);

        jMenuItemActualizarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItemActualizarCliente.setText("Actualizar Datos Cliente");
        jMenuItemActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemActualizarCliente);

        jMenuItemVisualizarClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItemVisualizarClientes.setText("Visualizar Clientes");
        jMenuItemVisualizarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemVisualizarClientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Empleados");

        jMenuItemRegistroEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemRegistroEmpleado.setText("Registrar Nuevo Empleado");
        jMenuItemRegistroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRegistroEmpleado);

        jMenuItemActualizarEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemActualizarEmpleado.setText("Actualizar Datos Empleado");
        jMenuItemActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemActualizarEmpleado);

        jMenuItemDespidoEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemDespidoEmpleado.setText("Despedir Empleado");
        jMenuItemDespidoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDespidoEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDespidoEmpleado);

        jMenuItemVisualizarEmpleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemVisualizarEmpleados.setText("Visualizar Empleados");
        jMenuItemVisualizarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarEmpleadosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemVisualizarEmpleados);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Producto/Servicio");

        jMenuItemAgregarProductoServicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemAgregarProductoServicio.setText("Agregar un Producto/Servicio");
        jMenuItemAgregarProductoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarProductoServicioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAgregarProductoServicio);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem1.setText("Actualizar Datos Producto/Servicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItemVisualizarProductoServicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemVisualizarProductoServicio.setText("Visualizar Productos y Servicios");
        jMenuItemVisualizarProductoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarProductoServicioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemVisualizarProductoServicio);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Operaciones");

        jMenuItemCrearReporte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemCrearReporte.setText("Crear Reporte");
        jMenuItemCrearReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearReporteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemCrearReporte);

        jMenuItemEstadoReporte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemEstadoReporte.setText("Estado Reporte");
        jMenuItemEstadoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadoReporteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemEstadoReporte);

        jMenuItemVisualizarReporte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemVisualizarReporte.setText("Visualizar Reporte");
        jMenuItemVisualizarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarReporteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemVisualizarReporte);

        jMenuItemAgregarCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemAgregarCategoria.setText("Agregar Categoria");
        jMenuItemAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAgregarCategoria);

        jMenuItemActualizarCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemActualizarCategoria.setText("Actualizar Categoria");
        jMenuItemActualizarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemActualizarCategoria);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(89, 89, 89)
                .addComponent(jButton1)
                .addGap(346, 346, 346))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCrearVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearVentaActionPerformed
        Ventas v= new Ventas();
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItemCrearVentaActionPerformed

    private void jMenuItemVisualizarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarVentasActionPerformed
       VisualizarVentas VsV= new VisualizarVentas();
        VsV.setVisible(true);
    }//GEN-LAST:event_jMenuItemVisualizarVentasActionPerformed

    private void jMenuItemEstadoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadoVentasActionPerformed
        EstadoVentas ev= new EstadoVentas();
        ev.setVisible(true);
    }//GEN-LAST:event_jMenuItemEstadoVentasActionPerformed

    private void jMenuItemIniciarLLamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIniciarLLamadaActionPerformed

       Llamadas l= new Llamadas();
        l.setVisible(true); 
        
    }//GEN-LAST:event_jMenuItemIniciarLLamadaActionPerformed

    private void jMenuItemHistorialLlamadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistorialLlamadasActionPerformed

       HistorialLlamadas hl= new HistorialLlamadas();
        hl.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemHistorialLlamadasActionPerformed

    private void jMenuItemRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroClienteActionPerformed
        Clientes c= new Clientes();
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistroClienteActionPerformed

    private void jMenuItemActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarClienteActionPerformed
        ActualizarClientes ac= new ActualizarClientes();
        ac.setVisible(true);
    }//GEN-LAST:event_jMenuItemActualizarClienteActionPerformed

    private void jMenuItemVisualizarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarClientesActionPerformed
        VisualizarClientes rc= new VisualizarClientes();
        rc.setVisible(true);
    }//GEN-LAST:event_jMenuItemVisualizarClientesActionPerformed

    private void jMenuItemRegistroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroEmpleadoActionPerformed
        Empleados e = new Empleados();
        e.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistroEmpleadoActionPerformed

    private void jMenuItemActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarEmpleadoActionPerformed
        ActualizarEmpleado ace = new ActualizarEmpleado();
        ace.setVisible(true);
    }//GEN-LAST:event_jMenuItemActualizarEmpleadoActionPerformed

    private void jMenuItemDespidoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDespidoEmpleadoActionPerformed
        DespidoEmpleado de = new DespidoEmpleado();
        de.setVisible(true);
    }//GEN-LAST:event_jMenuItemDespidoEmpleadoActionPerformed

    private void jMenuItemVisualizarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarEmpleadosActionPerformed
        VisualizarEmpleados ve= new VisualizarEmpleados();
        ve.setVisible(true);
    }//GEN-LAST:event_jMenuItemVisualizarEmpleadosActionPerformed

    private void jMenuItemAgregarProductoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarProductoServicioActionPerformed

        ProductoServicio ps= new ProductoServicio();
        ps.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemAgregarProductoServicioActionPerformed

    private void jMenuItemContratarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContratarServicioActionPerformed
        ContratarServicios s= new ContratarServicios();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItemContratarServicioActionPerformed

    private void jMenuItemCancelarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCancelarServicioActionPerformed
        CancelarServicio cs= new CancelarServicio();
        cs.setVisible(true);
    }//GEN-LAST:event_jMenuItemCancelarServicioActionPerformed

    private void jMenuItemVisualizarServiciosVigentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarServiciosVigentesActionPerformed
        VisualizarContrataciones vc=new VisualizarContrataciones();
        vc.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItemVisualizarServiciosVigentesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemVisualizarProductoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarProductoServicioActionPerformed

        
    }//GEN-LAST:event_jMenuItemVisualizarProductoServicioActionPerformed

    private void jMenuItemCrearReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearReporteActionPerformed
       
    }//GEN-LAST:event_jMenuItemCrearReporteActionPerformed

    private void jMenuItemEstadoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadoReporteActionPerformed
       
    }//GEN-LAST:event_jMenuItemEstadoReporteActionPerformed

    private void jMenuItemVisualizarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarReporteActionPerformed
        
    }//GEN-LAST:event_jMenuItemVisualizarReporteActionPerformed

    private void jMenuItemAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarCategoriaActionPerformed
        
    }//GEN-LAST:event_jMenuItemAgregarCategoriaActionPerformed

    private void jMenuItemActualizarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarCategoriaActionPerformed
        
    }//GEN-LAST:event_jMenuItemActualizarCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuEmpleado().setVisible(true);
//            }
//        });

        MenuPrincipal mp = new MenuPrincipal();
        mp.setExtendedState(MAXIMIZED_BOTH);
        mp.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemActualizarCategoria;
    private javax.swing.JMenuItem jMenuItemActualizarCliente;
    private javax.swing.JMenuItem jMenuItemActualizarEmpleado;
    private javax.swing.JMenuItem jMenuItemAgregarCategoria;
    private javax.swing.JMenuItem jMenuItemAgregarProductoServicio;
    private javax.swing.JMenuItem jMenuItemCancelarServicio;
    private javax.swing.JMenuItem jMenuItemContratarServicio;
    private javax.swing.JMenuItem jMenuItemCrearReporte;
    private javax.swing.JMenuItem jMenuItemCrearVenta;
    private javax.swing.JMenuItem jMenuItemDespidoEmpleado;
    private javax.swing.JMenuItem jMenuItemEstadoReporte;
    private javax.swing.JMenuItem jMenuItemEstadoVentas;
    private javax.swing.JMenuItem jMenuItemHistorialLlamadas;
    private javax.swing.JMenuItem jMenuItemIniciarLLamada;
    private javax.swing.JMenuItem jMenuItemRegistroCliente;
    private javax.swing.JMenuItem jMenuItemRegistroEmpleado;
    private javax.swing.JMenuItem jMenuItemVisualizarClientes;
    private javax.swing.JMenuItem jMenuItemVisualizarEmpleados;
    private javax.swing.JMenuItem jMenuItemVisualizarProductoServicio;
    private javax.swing.JMenuItem jMenuItemVisualizarReporte;
    private javax.swing.JMenuItem jMenuItemVisualizarServiciosVigentes;
    private javax.swing.JMenuItem jMenuItemVisualizarVentas;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
